/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/merchant': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current merchant */
    get: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A single merchant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Merchant'];
          };
        };
        /** @description Merchant not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update merchant information */
    put: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /**
             * @description Merchant name
             * @example Updated Acme Corporation
             */
            name?: string;
            /**
             * @description Merchant website URL
             * @example https://updated-acme.com
             */
            website?: string;
          };
        };
      };
      responses: {
        /** @description Merchant updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Merchant'];
          };
        };
        /** @description Bad request - Invalid input data */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unprocessable entity - Validation errors */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user */
    get: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current authenticated user */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MerchantUser'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    /** Update current user's password */
    put: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description current password */
            current_password: string;
            /** @description new password */
            password: string;
            /** @description new password confirmation */
            password_confirmation: string;
          };
        };
      };
      responses: {
        /** @description Password updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid password format or missing parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Unauthorized or incorrect current password */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all users for current merchant */
    get: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of users */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MerchantUser'][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login a user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description User logged in successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              token?: string;
              user?: components['schemas']['MerchantUser'];
            };
          };
        };
        /** @description Missing required parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ParameterMissingError'];
          };
        };
        /** @description Invalid credentials */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Merchant not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['NotFoundError'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Logout a user */
    delete: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User logged out successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/offers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all offers */
    get: {
      parameters: {
        query?: {
          page?: number | string;
          per_page?: number | string;
          status?: 'draft' | 'pending_approval' | 'active' | 'expired';
        };
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of offers */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              offers?: components['schemas']['OfferList'][];
              status_counts?: {
                /** @description Number of offers in draft status */
                draft?: number;
                /** @description Number of offers pending approval */
                pending_approval?: number;
                /** @description Number of active offers */
                active?: number;
                /** @description Number of expired offers (sum of rejected and completed) */
                expired?: number;
              };
              /** @description Aggregate metrics across all offers for this merchant */
              metrics?: {
                /**
                 * @description Total revenue generated across all offers for this merchant
                 * @example 15000
                 */
                total_revenue_generated?: number;
                /**
                 * @description Total number of redemptions across all offers for this merchant
                 * @example 150
                 */
                total_redemptions?: number;
                /**
                 * @description Total budget used across all offers for this merchant
                 * @example 1500
                 */
                total_budget_used?: number;
              };
              pagination?: components['schemas']['pagination'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** Create a new offer */
    post: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateOffer'];
        };
      };
      responses: {
        /** @description Offer created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Offer'];
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden - Insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/offers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an offer by ID */
    get: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A single offer with rules */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Offer'];
          };
        };
        /** @description Offer not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update an existing offer */
    put: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @example 10% off all items */
            name?: string;
            /** @example Get 10% off on all items in the store */
            description?: string;
            /** @default true */
            is_draft?: boolean;
            /**
             * @description Tenant ID that this offer applies to
             * @example 1
             */
            tenant_id?: number;
            /**
             * @description Maximum number of redemptions allowed for this offer
             * @example 1000
             */
            redemptions_count_limit?: number;
            /**
             * @description Maximum budget limit for this offer in currency units
             * @example 50000
             */
            budget_limit?: number;
            /**
             * Format: date-time
             * @description Required for non-draft offers to set status to pending_approval
             * @example 2024-06-01T00:00:00Z
             */
            start_date?: string;
            /**
             * Format: date-time
             * @description Required for non-draft offers to set status to pending_approval
             * @example 2024-12-31T23:59:59Z
             */
            end_date?: string;
            /**
             * @description Terms and conditions for the offer
             * @example This offer is valid for a limited time only. Cashback will be credited within 24-48 hours.
             */
            terms_and_conditions?: string;
            /** @example [
             *       {
             *         "transaction_count_lower_limit": 1,
             *         "transaction_count_upper_limit": 10,
             *         "transaction_amount_lower_limit": 100,
             *         "transaction_amount_upper_limit": 1000,
             *         "number_of_days": 30,
             *         "target_brand_ids": [
             *           1,
             *           2,
             *           3
             *         ],
             *         "target_category_ids": [
             *           1,
             *           2
             *         ],
             *         "target_sub_category_ids": [
             *           1
             *         ]
             *       }
             *     ] */
            rules?: {
              /** @example 1 */
              transaction_count_lower_limit: number | null;
              /** @example 10 */
              transaction_count_upper_limit: number | null;
              /** @example 100 */
              transaction_amount_lower_limit: number | null;
              /** @example 1000 */
              transaction_amount_upper_limit: number | null;
              /**
               * @description Number of days for the offer rule (1-365)
               * @example 30
               */
              number_of_days?: number;
              /**
               * @description Optional array of brand IDs. At least one of target_brand_ids, target_category_ids, or target_sub_category_ids must be provided.
               * @example [
               *       1,
               *       2,
               *       3
               *     ]
               */
              target_brand_ids?: number[];
              /**
               * @description Optional array of category IDs. At least one of target_brand_ids, target_category_ids, or target_sub_category_ids must be provided.
               * @example [
               *       1,
               *       2
               *     ]
               */
              target_category_ids?: number[];
              /**
               * @description Optional array of sub-category IDs. At least one of target_brand_ids, target_category_ids, or target_sub_category_ids must be provided.
               * @example [
               *       1
               *     ]
               */
              target_sub_category_ids?: number[];
            }[];
            /**
             * @description Required for non-draft offers. Optional for draft offers.
             * @example {
             *       "cashback_type": "fixed",
             *       "cashback_config": {
             *         "cashback_amount": 10.5,
             *         "minimum_transaction_value": 100
             *       }
             *     }
             */
            cashback_rule?: {
              /**
               * @example fixed
               * @enum {string}
               */
              cashback_type?: 'fixed' | 'percentage' | 'tiered';
              cashback_config?: components['schemas']['CashbackRuleConfig'];
            };
            /** @description Optional array of offer attachments with images */
            offer_attachments_attributes?: {
              /** @description ID of existing attachment (for updates) */
              id?: number;
              /**
               * Format: binary
               * @description Image file to upload
               */
              image?: string;
              /** @description Set to true to delete this attachment */
              _destroy?: boolean;
            }[];
          };
        };
      };
      responses: {
        /** @description Offer updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Offer'];
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden - Insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Offer not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unprocessable entity - Offer can only be modified when status is 'draft' or 'pending_approval' */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    /** Delete an offer */
    delete: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Offer deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Offer not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/offers/{id}/add_attachments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload a single attachment to an offer */
    post: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            /**
             * Format: binary
             * @description Image file to upload
             */
            image: string;
            /**
             * @description Type of attachment (banner, promotional, or logo)
             * @enum {string}
             */
            attachment_type: 'banner' | 'promotional' | 'logo';
          };
        };
      };
      responses: {
        /** @description Attachment added successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OfferAttachment'];
          };
        };
        /** @description Bad request - Image and attachment_type are required */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Offer not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Validation error or offer status restriction - Offer can only be modified when status is 'draft' or 'pending_approval' */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/offers/{id}/remove_attachments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Bulk delete attachments from an offer */
    delete: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /**
             * @description Array of attachment IDs to remove
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            attachment_ids: number[];
          };
        };
      };
      responses: {
        /** @description Attachments deleted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /**
               * @description Success message
               * @example Successfully deleted 3 attachment(s)
               */
              message?: string;
              /**
               * @description Number of attachments deleted
               * @example 3
               */
              deleted_count?: number;
            };
          };
        };
        /** @description Bad request - Attachment IDs are required */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Offer not found or no attachments found with provided IDs */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Failed to remove attachment or offer status restriction - Offer can only be modified when status is 'draft' or 'pending_approval' */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/brands': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all brands */
    get: {
      parameters: {
        query: {
          search: string;
          page?: number;
          per_page?: number;
        };
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of brands */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              brands?: components['schemas']['Brand'][];
              pagination?: components['schemas']['pagination'];
            };
          };
        };
        /** @description Bad request - Invalid parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all categories */
    get: {
      parameters: {
        query?: {
          search?: string;
        };
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of categories */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              categories?: components['schemas']['Category'][];
            };
          };
        };
        /** @description Bad request - Invalid parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/sub_categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all sub categories */
    get: {
      parameters: {
        query: {
          category_id: number;
          search?: string;
        };
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of sub categories */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              sub_categories?: components['schemas']['SubCategory'][];
            };
          };
        };
        /** @description Bad request - Invalid parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/tenants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all tenants */
    get: {
      parameters: {
        query?: {
          page?: number;
          per_page?: number;
        };
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of tenants */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              tenants?: components['schemas']['Tenant'][];
              pagination?: components['schemas']['pagination'];
            };
          };
        };
        /** @description Bad request - Invalid parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/rule_target_count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Get target customer count for offer rule validation */
    post: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /**
             * @description Tenant ID to get customer count for
             * @example 1
             */
            tenant_id: number;
            /** @description Offer rule object to calculate customer count */
            offer_rule: {
              /**
               * @description Lower limit for transaction count
               * @example 1
               */
              transaction_count_lower_limit?: number | null;
              /**
               * @description Upper limit for transaction count
               * @example 10
               */
              transaction_count_upper_limit?: number | null;
              /**
               * @description Lower limit for transaction amount
               * @example 100
               */
              transaction_amount_lower_limit?: number | null;
              /**
               * @description Upper limit for transaction amount
               * @example 1000
               */
              transaction_amount_upper_limit?: number | null;
              /**
               * @description Number of days for the offer rule
               * @example 30
               */
              number_of_days?: number;
              /**
               * @description Array of target brand IDs
               * @example [
               *       1,
               *       2,
               *       3
               *     ]
               */
              target_brand_ids?: number[] | null;
              /**
               * @description Array of target category IDs
               * @example [
               *       1,
               *       2
               *     ]
               */
              target_category_ids?: number[] | null;
              /**
               * @description Array of target sub-category IDs
               * @example [
               *       1,
               *       2,
               *       3
               *     ]
               */
              target_sub_category_ids?: number[] | null;
            };
          };
        };
      };
      responses: {
        /** @description Customer count retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /**
               * @description Number of customers matching the offer rule criteria
               * @example 1500
               */
              customer_count?: number;
            };
          };
        };
        /** @description Invalid request body - missing required parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unprocessable entity - failed to get customer count */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/add_merchant_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add a new merchant ID */
    post: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /**
             * @description External merchant ID to add
             * @example MERCHANT-123456
             */
            merchant_id: string;
          };
        };
      };
      responses: {
        /** @description Merchant ID added successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example [
               *       "MERCHANT-123456",
               *       "MERCHANT-789012"
               *     ] */
              merchant_ids?: string[];
            };
          };
        };
        /** @description Bad request - Merchant ID is required */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unprocessable entity - Merchant ID already exists */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/remove_merchant_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Remove a merchant ID */
    post: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /**
             * @description External merchant ID to remove
             * @example MERCHANT-123456
             */
            merchant_id: string;
          };
        };
      };
      responses: {
        /** @description Merchant ID removed successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad request - Merchant ID is required */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Merchant ID not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/upload_logo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload merchant logo */
    post: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            /**
             * Format: binary
             * @description Logo image file (JPEG, PNG, or GIF)
             */
            logo: string;
          };
        };
      };
      responses: {
        /** @description Logo uploaded successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /**
               * @description URL of the uploaded logo
               * @example https://example.com/logo.png
               */
              logo_url?: string;
              /** @example Logo uploaded successfully */
              message?: string;
            };
          };
        };
        /** @description Bad request - No logo file provided */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unprocessable entity - Invalid file format or size */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/merchant/delete_logo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete merchant logo */
    delete: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logo deleted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example Logo deleted successfully */
              message?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No logo found to delete */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenant/offers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all tenant's offers */
    get: {
      parameters: {
        query?: {
          page?: number | string;
          per_page?: number | string;
          status?: 'pending_approval' | 'active' | 'expired';
        };
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of offers */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              offers?: components['schemas']['TenantOfferList'][];
              status_counts?: {
                /** @description Number of offers pending approval */
                pending_approval: number;
                /** @description Number of active offers */
                active: number;
                /** @description Number of expired offers (sum of rejected and completed) */
                expired: number;
              };
              metrics?: components['schemas']['Metrics'];
              pagination?: components['schemas']['pagination'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenant/offers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a tenant's offer by ID */
    get: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A single offer with full offer's details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TenantOffer'];
          };
        };
        /** @description Offer not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenant/offers/{id}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update a tenant's offer status - accept */
    put: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Offer updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TenantOffer'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden - Insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Offer not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Failed to update offer */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenant/offers/{id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update a tenant's offer status - reject */
    put: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Offer updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TenantOffer'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden - Insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Offer not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Failed to update offer */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenant/cashbacks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all tenant's cashbacks */
    get: {
      parameters: {
        query?: {
          /** @description Filter cashbacks by status */
          status?: 'pending_approval' | 'approved' | 'declined';
          page?: number;
          per_page?: number;
        };
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of cashbacks for the tenant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              cashbacks?: components['schemas']['Cashback'][];
              status_counts?: {
                pending_approval?: number;
                approved?: number;
                declined?: number;
              };
              pagination?: components['schemas']['pagination'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unprocessable entity */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenant/cashbacks/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a tenant's cashback by ID */
    get: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A single cashback with full details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Cashback'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Cashback not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unprocessable entity */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    /** Update a tenant's cashback status */
    put: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            cashback: {
              /**
               * @description New status for the cashback
               * @enum {string}
               */
              status: 'pending_approval' | 'approved' | 'declined';
            };
          };
        };
      };
      responses: {
        /** @description Cashback updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Cashback'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Cashback not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Failed to update cashback */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenant/cashbacks/{id}/submit_feedback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit feedback for a cashback */
    post: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            feedback: {
              /**
               * @description Type of feedback being submitted
               * @example wrong_calculation
               * @enum {string}
               */
              feedback_type: 'wrong_calculation' | 'refunded';
              /**
               * @description Detailed feedback message
               * @example The cashback amount calculated seems incorrect. I was expecting $15.00 but received $10.00.
               */
              message: string;
            };
          };
        };
      };
      responses: {
        /** @description Feedback submitted successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CashbackFeedback'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Cashback not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Failed to submit feedback */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenant/cashbacks/{id}/delete_feedback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete feedback for a cashback */
    delete: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Feedback deleted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example Feedback deleted successfully */
              message?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Cashback not found or no feedback exists */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Failed to delete feedback */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenant/recalculate_cashbacks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Recalculate cashbacks by IDs or offer ID */
    post: {
      parameters: {
        query?: never;
        header?: {
          Authorization?: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json':
            | {
                /**
                 * @description Array of cashback IDs to recalculate
                 * @example [
                 *       1,
                 *       2,
                 *       3
                 *     ]
                 */
                cashback_ids: number[];
              }
            | {
                /**
                 * @description ID of the offer to recalculate all cashbacks for
                 * @example 1
                 */
                offer_id: number;
              };
        };
      };
      responses: {
        /** @description Cashback recalculation job queued successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example Cashback recalculation job has been queued */
              message: string;
              /** @example [
               *       1,
               *       2,
               *       3
               *     ] */
              cashback_ids?: ((number[] | null) | null) | null;
              /** @example 1 */
              offer_id?: ((number | null) | null) | null;
            };
          };
        };
        /** @description Bad request - invalid parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /**
       * @description Error message
       * @example Service temporarily unavailable
       */
      error: string;
    };
    ValidationError: {
      /**
       * @description Error message
       * @example Validation failed
       */
      error: string;
      /**
       * @description List of validation error messages
       * @example [
       *       "Email can't be blank",
       *       "Password is too short (minimum is 6 characters)"
       *     ]
       */
      details: string[];
    };
    ParameterMissingError: {
      /**
       * @description Error message indicating which parameter is missing
       * @example Missing required parameter: auth
       */
      error: string;
    };
    NotFoundError: {
      /**
       * @description Error message
       * @example Resource not found
       */
      error: string;
    };
    Merchant: {
      id?: number;
      name?: string | null;
      logo?: string | null;
      website?: string | null;
      /**
       * @description Array of external merchant IDs
       * @example [
       *       "MERCHANT-123456",
       *       "MERCHANT-789012"
       *     ]
       */
      merchant_ids?: string[];
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    MerchantUser: {
      id?: number;
      name?: string | null;
      /** Format: email */
      email?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    /** @example {
     *       "name": "10% off all items",
     *       "description": "Get 10% off on all items in the store",
     *       "is_draft": false,
     *       "tenant_id": 1,
     *       "redemptions_count_limit": 1000,
     *       "budget_limit": 50000,
     *       "start_date": "2025-09-01T00:00:00Z",
     *       "end_date": "2025-12-31T23:59:59Z",
     *       "rules": [
     *         {
     *           "transaction_count_lower_limit": 1,
     *           "transaction_count_upper_limit": 10,
     *           "transaction_amount_lower_limit": 100,
     *           "transaction_amount_upper_limit": 1000,
     *           "number_of_days": 30,
     *           "target_brand_ids": [
     *             1,
     *             2,
     *             3
     *           ],
     *           "target_category_ids": [
     *             1,
     *             2
     *           ],
     *           "target_sub_category_ids": [
     *             1
     *           ]
     *         }
     *       ],
     *       "cashback_rule": {
     *         "cashback_type": "fixed",
     *         "cashback_config": {
     *           "cashback_amount": 10.5,
     *           "minimum_transaction_value": 100
     *         }
     *       }
     *     } */
    CreateOffer: {
      /** @example 10% off all items */
      name: string;
      /** @example Get 10% off on all items in the store */
      description: string;
      /** @default true */
      is_draft: boolean;
      /**
       * @description Tenant ID that this offer applies to
       * @example 1
       */
      tenant_id: number;
      /**
       * @description Maximum number of redemptions allowed for this offer
       * @example 1000
       */
      redemptions_count_limit: number;
      /**
       * @description Maximum budget limit for this offer in currency units
       * @example 50000
       */
      budget_limit: number;
      /**
       * Format: date-time
       * @description Required for non-draft offers to set status to pending_approval
       * @example 2024-06-01T00:00:00Z
       */
      start_date?: string;
      /**
       * Format: date-time
       * @description Required for non-draft offers to set status to pending_approval
       * @example 2024-12-31T23:59:59Z
       */
      end_date?: string;
      /**
       * @description Terms and conditions for the offer
       * @example This offer is valid for a limited time only. Cashback will be credited within 24-48 hours.
       */
      terms_and_conditions?: string;
      /** @example [
       *       {
       *         "transaction_count_lower_limit": 1,
       *         "transaction_count_upper_limit": 10,
       *         "transaction_amount_lower_limit": 100,
       *         "transaction_amount_upper_limit": 1000,
       *         "number_of_days": 30,
       *         "target_brand_ids": [
       *           1,
       *           2,
       *           3
       *         ],
       *         "target_category_ids": [
       *           1,
       *           2
       *         ],
       *         "target_sub_category_ids": [
       *           1
       *         ]
       *       }
       *     ] */
      rules?: {
        /** @example 1 */
        transaction_count_lower_limit: number | null;
        /** @example 10 */
        transaction_count_upper_limit: number | null;
        /** @example 100 */
        transaction_amount_lower_limit: number | null;
        /** @example 1000 */
        transaction_amount_upper_limit: number | null;
        /**
         * @description Number of days for the offer rule (1-90). Required for non-draft offers. Defaults to 30.
         * @example 30
         */
        number_of_days?: number;
        /**
         * @description Optional array of brand IDs. At least one of target_brand_ids, target_category_ids, or target_sub_category_ids must be provided.
         * @example [
         *       1,
         *       2,
         *       3
         *     ]
         */
        target_brand_ids?: number[] | null;
        /**
         * @description Optional array of category IDs. At least one of target_brand_ids, target_category_ids, or target_sub_category_ids must be provided.
         * @example [
         *       1,
         *       2
         *     ]
         */
        target_category_ids?: number[] | null;
        /**
         * @description Optional array of sub-category IDs. At least one of target_brand_ids, target_category_ids, or target_sub_category_ids must be provided.
         * @example [
         *       1
         *     ]
         */
        target_sub_category_ids?: number[] | null;
      }[];
      /**
       * @description Required for non-draft offers. Optional for draft offers.
       * @example {
       *       "cashback_type": "fixed",
       *       "cashback_config": {
       *         "cashback_amount": 10.5,
       *         "minimum_transaction_value": 100
       *       }
       *     }
       */
      cashback_rule?: {
        /**
         * @example fixed
         * @enum {string}
         */
        cashback_type?: 'fixed' | 'percentage' | 'tiered';
        cashback_config?: components['schemas']['CashbackRuleConfig'];
      };
    };
    Offer: {
      id?: number;
      name?: string;
      description?: string;
      merchant_id?: number;
      merchant_name?: string;
      /** @enum {string} */
      status?: 'draft' | 'pending_approval' | 'rejected' | 'active' | 'completed';
      /**
       * @description Tenant ID that this offer applies to
       * @example 1
       */
      tenant_id?: number;
      /**
       * @description Name of the tenant that this offer applies to
       * @example Bank ABC
       */
      tenant_name?: string | null;
      /**
       * @description Maximum number of redemptions allowed for this offer
       * @example 1000
       */
      redemptions_count_limit?: number;
      /**
       * @description Maximum budget limit for this offer in currency units
       * @example 50000
       */
      budget_limit?: number;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      end_date?: string | null;
      /** @description Terms and conditions for the offer */
      terms_and_conditions?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      offer_rules?: components['schemas']['OfferRule'][];
      cashback_rule?: components['schemas']['CashbackRule'];
      offer_attachments?: components['schemas']['OfferAttachment'][];
      metrics?: components['schemas']['Metrics'];
    };
    TenantOffer: {
      id?: number;
      name?: string;
      description?: string;
      merchant_id?: number;
      merchant_name?: string;
      /** @enum {string} */
      status?: 'pending_approval' | 'rejected' | 'active' | 'completed';
      /**
       * @description Tenant ID that this offer applies to
       * @example 1
       */
      tenant_id?: number;
      /**
       * @description Maximum number of redemptions allowed for this offer
       * @example 1000
       */
      redemptions_count_limit?: number;
      /**
       * @description Maximum budget limit for this offer in currency units
       * @example 50000
       */
      budget_limit?: number;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      end_date?: string | null;
      /** @description Terms and conditions for the offer */
      terms_and_conditions?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      rules?: components['schemas']['OfferRule'][];
      cashback_rule?: components['schemas']['CashbackRule'];
      offer_attachments?: components['schemas']['OfferAttachment'][];
    };
    /** @description Required for non-draft offers. Optional for draft offers. */
    OfferRule: {
      id?: number;
      offer_id?: number;
      transaction_count_lower_limit?: number | null;
      transaction_count_upper_limit?: number | null;
      transaction_amount_lower_limit?: number | null;
      transaction_amount_upper_limit?: number | null;
      /** @description Number of days for the offer rule (1-90). Defaults to 30. */
      number_of_days?: number;
      /**
       * @description Hash mapping brand IDs to brand names
       * @example {
       *       "1": "Brand 1",
       *       "2": "Brand 2"
       *     }
       */
      target_brands?: {
        [key: string]: string;
      } | null;
      /**
       * @description Hash mapping category IDs to category names
       * @example {
       *       "1": "Category 1",
       *       "2": "Category 2"
       *     }
       */
      target_categories?: {
        [key: string]: string;
      } | null;
      /**
       * @description Hash mapping sub-category IDs to sub-category names
       * @example {
       *       "1": "Sub-category 1",
       *       "2": "Sub-category 2"
       *     }
       */
      target_sub_categories?: {
        [key: string]: string;
      } | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    } | null;
    Brand: {
      id?: number;
      name?: string;
      logo?: string | null;
      website?: string | null;
    };
    Category: {
      id?: number;
      name?: string;
      icon?: string | null;
      icon_dark?: string | null;
    };
    SubCategory: {
      id?: number;
      name?: string;
    };
    Tenant: {
      /**
       * @description Unique identifier for the tenant
       * @example 1
       */
      id?: number;
      /**
       * @description Name of the tenant
       * @example Bank ABC
       */
      name?: string;
    };
    OfferList: {
      id?: number;
      name?: string;
      description?: string;
      merchant_id?: number;
      merchant_name?: string;
      /** @description Name of the tenant that this offer applies to */
      tenant_name?: string | null;
      /** @enum {string} */
      status?: 'draft' | 'pending_approval' | 'rejected' | 'active' | 'completed';
      /**
       * @description Tenant ID that this offer applies to
       * @example 1
       */
      tenant_id?: number;
      /**
       * @description Maximum number of redemptions allowed for this offer
       * @example 1000
       */
      redemptions_count_limit?: number;
      /**
       * @description Maximum budget limit for this offer in currency units
       * @example 50000
       */
      budget_limit?: number;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      end_date?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      /** @description First attachment of the offer, if any */
      cover_image?: {
        /** @description Attachment ID */
        id?: number;
        /** @description URL to the attachment image */
        image_url?: string;
        /** @description Original filename of the image */
        image_filename?: string;
        /** @description MIME type of the image */
        image_content_type?: string;
        /** @description Size of the image in bytes */
        image_byte_size?: number;
      } | null;
      metrics?: components['schemas']['Metrics'];
    };
    TenantOfferList: {
      id?: number;
      name?: string;
      description?: string;
      merchant_id?: number;
      merchant_name?: string;
      /** @enum {string} */
      status?: 'pending_approval' | 'rejected' | 'active' | 'completed';
      /**
       * @description Tenant ID that this offer applies to
       * @example 1
       */
      tenant_id?: number;
      /**
       * @description Maximum number of redemptions allowed for this offer
       * @example 1000
       */
      redemptions_count_limit?: number;
      /**
       * @description Maximum budget limit for this offer in currency units
       * @example 50000
       */
      budget_limit?: number;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      end_date?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      metrics?: components['schemas']['Metrics'];
    };
    /** @description Required for non-draft offers. Optional for draft offers. */
    CashbackRule: {
      id?: number;
      offer_id?: number;
      /** @enum {string} */
      cashback_type?: 'fixed' | 'percentage' | 'tiered';
      cashback_config?: components['schemas']['CashbackRuleConfig'];
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    } | null;
    Cashback: {
      /**
       * @description Unique identifier for the cashback
       * @example 1
       */
      id?: number;
      /**
       * @description Unique transaction identifier
       * @example TXN-00000001
       */
      transaction_id?: string;
      /**
       * @description Customer identifier from the original system
       * @example CUST-00000001
       */
      customer_original_id?: string;
      /**
       * @description Amount of the original transaction
       * @example 100.00
       */
      transaction_amount?: string;
      /**
       * @description Amount of cashback earned
       * @example 10.00
       */
      cashback_amount?: string;
      /**
       * @description Current status of the cashback
       * @example pending_approval
       * @enum {string}
       */
      status?: 'pending_approval' | 'approved' | 'declined';
      /**
       * @description Tenant ID that this cashback belongs to
       * @example 123
       */
      tenant_id?: number;
      offer?: {
        /** @example 1 */
        id?: number;
        /** @example Test Offer */
        name?: string;
        /** @example This is a test offer description */
        description?: string;
        /** @example Merchant 1 */
        merchant_name?: string;
      };
      /** @description Feedback associated with this cashback, if any */
      cashback_feedback?: {
        /** @example 1 */
        id?: number;
        /**
         * @description The feedback message
         * @example Customer complaint about cashback calculation
         */
        feedback?: string;
        /**
         * @example wrong_calculation
         * @enum {string}
         */
        feedback_type?: 'wrong_calculation' | 'refunded';
        /** Format: date-time */
        created_at?: string;
      } | null;
      /**
       * Format: date-time
       * @description When the cashback was created
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description When the cashback was last updated
       */
      updated_at?: string;
    };
    /** @description Per-offer metrics for this specific offer */
    Metrics: {
      /**
       * @description Total revenue generated from this offer
       * @example 1500
       */
      revenue_generated?: number;
      /**
       * @description Number of redemptions for this offer
       * @example 15
       */
      redemptions_count?: number;
      /**
       * @description Total budget used for this offer
       * @example 150
       */
      budget_used?: number;
    };
    CashbackFeedback: {
      /**
       * @description Unique identifier for the feedback
       * @example 1
       */
      id?: number;
      /**
       * @description Type of feedback submitted
       * @example wrong_calculation
       * @enum {string}
       */
      feedback_type?: 'wrong_calculation' | 'refunded';
      /**
       * @description The feedback message
       * @example The cashback amount calculated seems incorrect. I was expecting $15.00 but received $10.00.
       */
      feedback?: string;
      /**
       * Format: date-time
       * @description When the feedback was created
       * @example 2024-01-15T10:30:00Z
       */
      created_at?: string;
    };
    OfferAttachment: {
      id: number;
      /**
       * @description Type of attachment
       * @example banner
       * @enum {string}
       */
      attachment_type: 'banner' | 'promotional' | 'logo';
      /**
       * @description URL to the attached image
       * @example /rails/active_storage/blobs/.../logo.png
       */
      image_url: string;
      /**
       * @description Original filename of the attached image
       * @example logo.png
       */
      image_filename: string;
      /**
       * @description MIME type of the attached image
       * @example image/png
       */
      image_content_type: string;
      /**
       * @description Size of the attached image in bytes
       * @example 1024
       */
      image_byte_size: number;
    };
    CashbackRuleConfig:
      | {
          /**
           * @description Fixed cashback amount in currency units
           * @example 10.5
           */
          cashback_amount: number;
          /**
           * @description Minimum transaction value required to earn cashback
           * @example 100
           */
          minimum_transaction_value: number;
        }
      | {
          /**
           * @description Cashback percentage (e.g., 5.0 for 5%)
           * @example 5
           */
          cashback_percentage: number;
          /**
           * @description Maximum cashback value that can be earned
           * @example 50
           */
          maximum_cashback_value: number;
        }
      | {
          /**
           * @description Minimum spending amount for this tier
           * @example 100
           */
          spending_tier: number;
          /**
           * @description Cashback percentage for this tier (e.g., 2.0 for 2%)
           * @example 2
           */
          cashback_percentage: number;
        }[];
    pagination: {
      current_page?: number;
      next_page?: number | null;
      previous_page?: number | null;
      total_pages?: number;
      per_page?: number;
      total_entries?: number;
    };
    Pagination: {
      current_page?: number;
      next_page?: number | null;
      previous_page?: number | null;
      total_pages?: number;
      per_page?: number;
      total_entries?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
